### PR TITLE
[WIP] Refactoring

### PR DESCRIPTION
**Pull request by nachtmaar**
- Update miniworld_playground examples to match impairment model

### CODE REVIEW

**Comment by nicopace** [comment]
Hi @nachtmaar .
I just stumble onto your project and it is sooo good, thanks so much for all the effort you put on it.
Just wanted to reach out to say we might start using it for the librerouter.org project, for testing the software it will come with, libremesh.org, in many simulated environments... and i am eager to see it working.
also commenting here just to cheer you ... happy to beta test if required.

**Comment by nachtmaar** [comment]
Hi @nicopace,
thanks for your comment. Really happy to hear that `miniworld` might be used by `librerouter`.
Let me know if you need help or something is not working as expected.
I guess you want to use a custom OpenWRT image. See the following explanation on [how to prepare it to be used by MiniWorld](https://miniworld-core.readthedocs.io/en/latest/usage/openwrt_custom.html).

If you wonder about performance you can check my [master thesis](https://nilstschmidt.de/media/2016_master_thesis_distributed_emulation_and_simulation_of_mobile_nodes_in_dynamic_networks_paper.pdf) or the published [paper](https://www.researchgate.net/publication/318928159_MiniWorld_Resource-aware_Distributed_Network_Emulation_via_Full_Virtualization)

Looking forward to hear from you.

**Comment by nachtmaar** [comment]
Btw, if you need any of the changes in this PR or plan to push changes upstream, let me know.
I stopped working on MiniWorld because I felt no-one is using it.
The PR was a big refactoring and should introduce a GraphQL API. However, I think I never finished

**Comment by nicopace** [comment]
Thanks so much for all the info @nachtmaar .
We are evaluating it in the context of @spiccinini work on doing a hardware setup for testing.
We were planning to do a flexible hardware setup, but it is extremely costly to do that... so maybe miniworld could be one middle ground for it.
We could run a cloud instance of it once per week testing the critical features, get a big amazon computer for one hour (i think it is quite cheap), and ran all these tests that require a lot of ram/cpu.

also, it would be interesting to use it to replicate issues that happen in the communities we serve so we can do regression tests on things that we fix (so they don't appear again).

Anyway... thanks for your contribution already... and if we use it we will definitely ping you :)

**Comment by nachtmaar** [comment]
If you want a cheap cloud instance, you could also use [Hetzner Cloud](https://www.hetzner.com/cloud).

Please keep in mind that at best you don't have nested virtualization. When running on a cloud instance, the hypervisor mostly does not pass the CPU virtualization feature (e.g. Intel VT-x). This means no KVM support. Instead Qemu emulates the CPU which is very slow compared to KVM.

The tests running on Travis however also just do emulation, but are slow too.

Maybe there is a cloud hoster which supports nested virtualization which also passes CPU virtualization through.

**Comment by nicopace** [comment]
Yes... having kvm is essential... we have a couple of hard nodes in a datacenter... but i am not sure if we want to stress them with these tests... we will see... it may happen in a few months probably!
I will for sure le you know about it... and if you are interested, would be awesome if you want to contribute :) (I asume you are busy... but who knows :)).
will ping you by then if not... thanks!

**Pull request closed without merging**
